### ISSUE TITLE
Lawnchair keeps crashing.

### ISSUE THREAD

**Issue by AmeChanRain** [Modded-ArrowOS-For-Switch/manifest#2]
```
02-28 05:34:40.707  5601  5601 D AndroidRuntime: Shutting down VM
02-28 05:34:40.709  5601  5601 E AndroidRuntime: FATAL EXCEPTION: main
02-28 05:34:40.709  5601  5601 E AndroidRuntime: Process: ch.deletescape.lawnchair.ci, PID: 5601
02-28 05:34:40.709  5601  5601 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ThreadedRenderer$FrameDrawingCallback;
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:668)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at ch.deletescape.lawnchair.animations.LawnchairAppTransitionManagerImpl.getOpeningWindowAnimators(LawnchairAppTransitionManagerImpl.kt:298)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:639)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.LauncherAppTransitionManagerImpl.access$300(LauncherAppTransitionManagerImpl.java:96)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.LauncherAppTransitionManagerImpl$2.onCreateAnimation(LauncherAppTransitionManagerImpl.java:220)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$0$LauncherAnimationRunner(LauncherAnimationRunner.java:56)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.launcher3.-$$Lambda$LauncherAnimationRunner$0IBM3bZEOrCXQUatxthdQPQcNQA.run(Unknown Source:6)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ThreadedRenderer$FrameDrawingCallback" on path: DexPathList[[zip file "/system/priv-app/Lawnchair/Lawnchair.apk"],nativeLibraryDirectories=[/system/priv-app/Lawnchair/lib/arm64, /system/priv-app/Lawnchair/Lawnchair.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]]
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-28 05:34:40.709  5601  5601 E AndroidRuntime: 	... 14 more
```

**Comment by AmeChanRain** [comment]
Switch to Launcher3
